### ISSUE TITLE
Would love a way to create a new file. 

### ISSUE THREAD

**Issue by Miley1** [csb6/editorial#1]
Currently, running something like:
$ editorial nonexistentfile.txt 
throws up:
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  Could not open given file: iostream error
Aborted

Am I missing something, or has this not been implemented yet?

Thank you for the program, I'd love to include it for my own personal project if file creation is added : )

**Comment by csb6** [comment]
@Miley1 Thanks for the feedback! I'm not sure why that wasn't one of the first features I added. The most recent commit should now be able to create and save to new files. If you have any issues, feel free to let me know about them.

Also: I recently made some changes to the build with the last few commits, so make sure to look at README.md when you update your installation. Hope that you have a great rest of your day!
